//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointment_Booking_MVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppointmentBookingEntities : DbContext
    {
        public AppointmentBookingEntities()
            : base("name=AppointmentBookingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAppointmentMaster> tblAppointmentMasters { get; set; }
        public virtual DbSet<tblDesignationMaster> tblDesignationMasters { get; set; }
        public virtual DbSet<tblDoctorMaster> tblDoctorMasters { get; set; }
        public virtual DbSet<tblSlotsIntervalMaster> tblSlotsIntervalMasters { get; set; }
    }
}
