//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointment_Booking_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoctorMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDoctorMaster()
        {
            this.tblAppointmentMasters = new HashSet<tblAppointmentMaster>();
        }
    
        public int Doctor_Id { get; set; }
        public string Doctor_Name { get; set; }
        public string Doctor_ContactNo_ { get; set; }
        public string Doctor_Email { get; set; }
        public byte[] Doctor_Image { get; set; }
        public int Doctor_Designation { get; set; }
        public System.TimeSpan From_Time { get; set; }
        public System.TimeSpan To_time { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<int> SlotIntervalID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAppointmentMaster> tblAppointmentMasters { get; set; }
        public virtual tblDesignationMaster tblDesignationMaster { get; set; }
        public virtual tblSlotsIntervalMaster tblSlotsIntervalMaster { get; set; }
    }
}
