//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointment_Booking_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppointmentMaster
    {
        public int Appointment_Id { get; set; }
        public System.DateTime Appointment_Date { get; set; }
        public string Appointment_Time { get; set; }
        public int Appointment_with { get; set; }
        public string Patient_Name { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        public virtual tblDoctorMaster tblDoctorMaster { get; set; }
    }
}
